# 3-4. Asynchronous operation and Exception handling
# 3-4-1. Asynchronous operation with `Promise`
- Callback Hell
```
fs.readfile('foo.txt', (err, data) => {
    console.log('foo:', data);
    fs.readfile('bar.txt', (err, data) => {
        console.log('bar:', data);
        fs.readfile('baz.txt', (err, data) => {
            console.log('baz:', data);
        });
    });
});
```
- Promise
```
promise.then().then().then();
```

## 3-4-2. `async` and `await`
- `async` keyword is used to define an asynchronous function
    - return value of `async` function is wrapped by `Promise.resolve()`
    - `await` can be used within `async` function
    - `await` waits `async` function to be resolved or rejected
- Top level `await` is not allowed
    - it is allowed since TypeScript 3.8, but not recommended

## 3-4-3. Exception handling
- `try-catch` is very primitive
    - cannot catch handle various types of errors
    - Ugly `if (e instanceof ...)` is required
